unbind C-b
set -g prefix C-Space
bind C-Space send-prefix
setw -g mouse on
# Statusbar dynamisch einfärben
set -g status-style '#{?client_prefix,bg=#d20f39,bg=#1e3a5f},fg=#cdd6f4'
set -g status-style '#{?client_prefix,bg=#d20f39,bg=#1e3a5f},fg=#cdd6f4'
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
set-option -g history-limit 999999
set -g mode-keys vi
